# Generated by Django 5.1 on 2024-10-14 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobportalsapp', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
