# Generated by Django 5.1 on 2024-10-15 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobportalsapp', '0006_contact'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='contact',
        ),
    ]
