# Generated by Django 5.1 on 2024-10-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobportalsapp', '0007_alter_contact_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon_class', models.CharField(max_length=255)),
                ('vacancy_count', models.IntegerField()),
            ],
        ),
    ]
