# Generated by Django 5.0.7 on 2024-08-07 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customeadmin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='joblist',
        ),
    ]
