# Generated by Django 5.1 on 2024-09-28 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0003_alter_jobseeker_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobseeker',
            table=None,
        ),
    ]
