# Generated by Django 5.1 on 2024-09-28 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0005_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobseeker',
            table='jobseeker',
        ),
    ]
