# Generated by Django 5.1 on 2024-09-30 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0006_alter_jobseeker_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='user_name',
            new_name='username',
        ),
    ]
