# Generated by Django 5.1 on 2024-09-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0007_rename_user_name_employer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('jobseeker', 'Job Seeker'), ('employer', 'Employer'), ('admin', 'Admin')], max_length=10),
        ),
    ]
