# Generated by Django 5.1 on 2024-10-02 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0008_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admin',
            table='admin',
        ),
    ]
