# Generated by Django 5.1 on 2024-10-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0009_alter_admin_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='username',
            field=models.CharField(default='admin', max_length=50),
            preserve_default=False,
        ),
    ]
