# Generated by Django 5.0.7 on 2024-08-03 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_managementapp', '0002_remove_customuser_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone_no',
            new_name='user_name',
        ),
    ]
