# Generated by Django 5.0.7 on 2024-08-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_managementapp', '0003_rename_phone_no_customuser_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
