# Generated by Django 5.0.7 on 2024-08-08 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_managementapp', '0005_joblist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joblist',
            old_name='jcity',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='joblist',
            old_name='jcountry',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='joblist',
            old_name='salary_max',
            new_name='max_salary_range',
        ),
        migrations.RenameField(
            model_name='joblist',
            old_name='salary_min',
            new_name='min_salary_range',
        ),
        migrations.RenameField(
            model_name='joblist',
            old_name='jname',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='joblist',
            old_name='jtime',
            new_name='type',
        ),
    ]
