# Generated by Django 5.0.7 on 2024-08-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_managementapp', '0006_rename_jcity_joblist_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblist',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
