# Generated by Django 5.0.7 on 2024-08-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_managementapp', '0007_alter_joblist_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblist',
            name='max_salary_range',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='min_salary_range',
            field=models.CharField(max_length=255),
        ),
    ]
