# Generated by Django 5.0.7 on 2024-08-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_managementapp', '0008_alter_joblist_max_salary_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblist',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='max_salary_range',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='min_salary_range',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
