# Generated by Django 5.0.7 on 2024-08-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_managementapp', '0009_alter_joblist_city_alter_joblist_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblist',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='max_salary_range',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='min_salary_range',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
