# Generated by Django 5.1 on 2024-09-05 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_managementapp', '0011_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
