# Generated by Django 5.1 on 2024-09-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_managementapp', '0012_delete_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobseeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('address', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'jobseeker',
            },
        ),
    ]
