# Generated by Django 5.1 on 2024-09-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_managementapp', '0013_jobseeker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=20)),
                ('employer_name', models.CharField(max_length=50)),
                ('employer_phone', models.CharField(max_length=50)),
                ('employer_email', models.EmailField(max_length=50)),
            ],
            options={
                'db_table': 'employer',
            },
        ),
    ]
