# Generated by Django 5.1 on 2024-09-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_managementapp', '0015_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
        migrations.AddField(
            model_name='employer',
            name='user_name',
            field=models.CharField(default='default_user', max_length=50),
            preserve_default=False,
        ),
    ]
