# Generated by Django 5.1 on 2024-09-30 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_managementapp', '0017_jobapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employer',
        ),
        migrations.DeleteModel(
            name='Jobseeker',
        ),
    ]
